#!/usr/bin/env tsx

/**
 * Generate CHANGELOG.md and INTERNAL_LOG.md from log.json entries
 *
 * This script reads entries from log.json, filters by date range,
 * and expects CHANGELOG_CONTENT and INTERNAL_LOG_CONTENT environment variables
 * (generated by Gemini) to write the final files.
 *
 * Usage:
 *   CHANGELOG_CONTENT="..." INTERNAL_LOG_CONTENT="..." tsx scripts/generate-release-notes.ts
 */

import fs from 'fs';
import path from 'path';

const CHANGELOG_FILE = path.join(process.cwd(), 'docs/releases/CHANGELOG.md');
const INTERNAL_LOG_FILE = path.join(
  process.cwd(),
  'docs/releases/INTERNAL_LOG.md'
);

function main() {
  const changelogContent = process.env.CHANGELOG_CONTENT;
  const internalLogContent = process.env.INTERNAL_LOG_CONTENT;

  if (!changelogContent || !internalLogContent) {
    console.error(
      '❌ Error: CHANGELOG_CONTENT and INTERNAL_LOG_CONTENT environment variables are required'
    );
    process.exit(1);
  }

  // Write CHANGELOG.md
  fs.writeFileSync(CHANGELOG_FILE, changelogContent);
  console.log('✅ Generated CHANGELOG.md');

  // Write INTERNAL_LOG.md
  fs.writeFileSync(INTERNAL_LOG_FILE, internalLogContent);
  console.log('✅ Generated INTERNAL_LOG.md');
}

main();
