name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn 4
        run: corepack prepare yarn@4.9.1 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Type check
        run: yarn typecheck

      - name: Run ESLint
        run: yarn lint

      - name: Check Prettier formatting
        run: yarn format:check

      - name: Ensure agent guides are synchronized
        run: |
          yarn sync:agents
          if ! git diff --exit-code CLAUDE.md AGENTS.md; then
            echo "❌ CLAUDE.md and AGENTS.md are not synchronized."
            echo "Run 'yarn sync:agents' and commit the changes."
            git diff CLAUDE.md AGENTS.md
            exit 1
          fi
          if ! git diff --exit-code; then
            echo "❌ Unexpected changes detected after running yarn sync:agents."
            git status --short
            exit 1
          fi
          echo "✅ Agent guides are synchronized"
