name: Sync Documentation
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'src/**/*.ts'
      - 'scripts/**/*.ts'
      - 'package.json'
      - 'tsconfig.json'
      - '.github/workflows/**/*.yml'
      - '.github/workflows/**/*.yaml'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: false

defaults:
  run:
    shell: 'bash'

jobs:
  doc-sync:
    if: github.actor != 'claude[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            This PR modifies TypeScript source code. Please:

            1. Review the changes in src/, scripts/, and .github/workflows/ directories
            2. Update CLAUDE.md if development commands or architecture changed
            3. Update README_original.md if needed
            4. Check if translation system changes require updates to docs/*_original.md files
            5. Ensure any new environment variables are documented
            6. Update package.json scripts documentation if new commands were added
            7. Create new documentation files if needed (e.g., docs/api_original.md, docs/setup_original.md)

            Focus on:
            - Translation workflow documentation (original files only)
            - Development setup instructions
            - GitHub Actions workflow changes
            - API changes in the translation system
            - Configuration options and environment variables
            - New features that need documentation

            Guidelines:
            - Only update or create original (*_original) documentation files
            - Suggest creating new docs files for major new features
            - Consider docs/troubleshooting_original.md for common issues
            - Consider docs/contributing_original.md for development guidelines
            - Translated versions will be handled by the translation workflow

            Commit any documentation updates to this PR branch.

          claude_args: |
            --model claude-sonnet-4-20250514 --allowedTools "Read,Write,Edit,Bash(git:*),Bash(yarn:*)"
